### ISSUE TITLE
Compatibility fix: replace `ssize_t` with `Py_ssize_t`

### ISSUE THREAD

**Issue by jbuonagurio** [Hintay/py-zebra-scanner-windows#2]
Hi, first of all I just wanted to say your library is *awesome*. Before I found this project I already started going through the motions of rewriting the Zebra SDK samples to make them 'nice' for a C++ application (regenerating the IDL, using `CComSafeArray`, proper RAII with smart pointers, exceptions...) and you've done all of that. This is really nice, modern Win32 ATL code which will inspire my own projects.

Just one small compatibility issue. `repr_wchar` at [zebra_scanner.cpp#L20](https://github.com/Hintay/py-zebra-scanner-windows/blob/c73655d/zebra-scanner/zebra_scanner.cpp#L20) uses `ssize_t` which is no longer defined starting with Python 3.9. The platform-specific type `Py_ssize_t` has been available since Python 2.5 ([PEP 353](https://peps.python.org/pep-0353/)) so it's safe to change it without version test macros.

**Comment by Hintay** [comment]
Thanks for the PR! I’ve merged it, and your fix looks great. Really appreciate your help in improving the project. Feel free to contribute anytime!
